### ISSUE TITLE
Support capacitor 4.0

### ISSUE THREAD

**Issue by Vshow101** [AlwaysLoveme/capacitor-plugin-safe-area#1]
Hi! Capacitor 4.0 has been released. Are there plans to support it?

**Comment by AlwaysLoveme** [comment]
> Hi! Capacitor 4.0 has been released. Are there plans to support it?

Hi, it is support Capacitor 4.x , nothing changed

**Comment by Vshow101** [comment]
> > Hi! Capacitor 4.0 has been released. Are there plans to support it?
> 
> Hi, it is support Capacitor 4.x , nothing changed

Thanks! Great work.
