### ISSUE TITLE
Support Capacitor v5

### ISSUE THREAD

**Issue by MaYoRr** [AlwaysLoveme/capacitor-plugin-safe-area#12]
The current version of the plugin does not work with Capacitor 5 and there is a conflict with npm i. Is there a plan to update this plugin for Capacitor 5?

**Comment by AlwaysLoveme** [comment]
> does not work with Capacitor 5

Thank you for using this plugin, Will plan to support v5 in a few days

**Comment by AlwaysLoveme** [comment]
> The current version of the plugin does not work with Capacitor 5 and there is a conflict with npm i. Is there a plan to update this plugin for Capacitor 5?

now it's suppport v5
