### ISSUE TITLE
Module not found: Error: Can't resolve './definitions'

### ISSUE THREAD

**Issue by AustineA** [AlwaysLoveme/capacitor-plugin-safe-area#13]
I'm getting this error on v2.0.0 capacitor 5

BREAKING CHANGE: The request './definitions' failed to resolve only because it was resolved as fully specified

**Comment by AlwaysLoveme** [comment]
> I'm getting this error on v2.0.0 capacitor 5
> 
> 
> 
> BREAKING CHANGE: The request './definitions' failed to resolve only because it was resolved as fully specified

Sorry,i can not reappear this error

**Comment by centrual** [comment]
Same here

![image](https://github.com/AlwaysLoveme/capacitor-plugin-safe-area/assets/2001424/034876ea-611c-492f-a146-1bcb5ec77399)

**Comment by AlwaysLoveme** [comment]
> Same here
> 
> 
> 
> ![image](https://github.com/AlwaysLoveme/capacitor-plugin-safe-area/assets/2001424/034876ea-611c-492f-a146-1bcb5ec77399)
> 
> 

Will fix this in a few days

**Comment by AlwaysLoveme** [comment]
> I'm getting this error on v2.0.0 capacitor 5
> 
> BREAKING CHANGE: The request './definitions' failed to resolve only because it was resolved as fully specified

fixed in latest version @centrual @AustineA

**Comment by centrual** [comment]
> 

Thank you so much for your efforts :)
