### ISSUE TITLE
Use 'self' when referencing to property 'implementation'

### ISSUE THREAD

**Issue by matteo-globe-protocol** [AlwaysLoveme/capacitor-plugin-safe-area#15]
你好 @AlwaysLoveme , 当Fastlane在CICD运行，我遇到这个小漏洞：

`reference to property 'implementation' in closure requires explicit use of 'self' to make capture semantics explicit`

https://github.com/AlwaysLoveme/capacitor-plugin-safe-area/blame/27de371ab59e58a63b0741a8cfff8dd4bc13e240/ios/Plugin/SafeAreaPlugin.swift#LL38C26-L38C26

能否知道需要等多久你能处理啊？

**Comment by AlwaysLoveme** [comment]
> 你好 @AlwaysLoveme , 当Fastlane在CICD运行，我遇到这个小漏洞：
> 
> `reference to property 'implementation' in closure requires explicit use of 'self' to make capture semantics explicit`
> 
> https://github.com/AlwaysLoveme/capacitor-plugin-safe-area/blame/27de371ab59e58a63b0741a8cfff8dd4bc13e240/ios/Plugin/SafeAreaPlugin.swift#LL38C26-L38C26
> 
> 能否知道需要等多久你能处理啊？

@matteo-globe-protocol 你好，已在最新版本中修复，感谢指出！

**Comment by matteo-globe-protocol** [comment]
那得谢你啦兄弟！你的fix解决了我们的问题！
