### ISSUE TITLE
Android safe area bottom doesn't work properly

### ISSUE THREAD

**Issue by LeGeek01** [AlwaysLoveme/capacitor-plugin-safe-area#16]
With capacitor v5 and android 13 (with buttons on nav bar enabled), the bottom safe aera is bigger than excepted. Elements fixed at bottom display in the system nav bar, and unable to be clicked

**Comment by blunt1337** [comment]
I had the same problem, check if my PR fixes it for you too https://github.com/AlwaysLoveme/capacitor-plugin-safe-area/pull/17
(you can try it with `"capacitor-plugin-safe-area": "https://github.com/blunt1337/capacitor-plugin-safe-area/archive/6daadd0bf380469e28276e112c5d803be4625247.tar.gz"` in the package.json)

**Comment by AlwaysLoveme** [comment]
> I had the same problem, check if my PR fixes it for you too #17 (you can try it with `"capacitor-plugin-safe-area": "https://github.com/blunt1337/capacitor-plugin-safe-area/archive/6daadd0bf380469e28276e112c5d803be4625247.tar.gz"` in the package.json)

merged in version 2.0.4

**Comment by LeGeek01** [comment]
version 2.0.4 fixed the issue
