### ISSUE TITLE
Update Github description

### ISSUE THREAD

**Issue by aeharding** [AlwaysLoveme/capacitor-plugin-safe-area#19]
Github description says "capacitor plugin to get safeArea info on Android and IOS, support Capacitor3/Capacitor4 "

But now it supports v5 so I suggest updating! Thanks for the great plugin!

**Comment by AlwaysLoveme** [comment]
> Github description says "capacitor plugin to get safeArea info on Android and IOS, support Capacitor3/Capacitor4 "
> 
> 
> 
> But now it supports v5 so I suggest updating! Thanks for the great plugin!

Already updated
