### ISSUE TITLE
Android wrong top insets values

### ISSUE THREAD

**Issue by EranGrin** [AlwaysLoveme/capacitor-plugin-safe-area#2]
Hello,
the values that I get for Android top insets seems to be higher than expected.

**Comment by AlwaysLoveme** [comment]
> Hello, the values that I get for Android top insets seems to be higher than expected.

top insets value  on Android is Statusbar Height

**Comment by AlwaysLoveme** [comment]
> Hello, the values that I get for Android top insets seems to be higher than expected.

OK ,   it  will fix in next version

**Comment by AlwaysLoveme** [comment]
> Hello, the values that I get for Android top insets seems to be higher than expected.

Hey, it is fixed in version V0.0.6, please upgrade the npm package
