### ISSUE TITLE
Bug: Running into Issues with Cap 5

### ISSUE THREAD

**Issue by mahyarmirrashed** [AlwaysLoveme/capacitor-plugin-safe-area#20]
I'm running Capacitor with the following versions:

```txt
		"@capacitor/android": "^5.2.2",
		"@capacitor/core": "^5.2.2",
		"@capacitor/device": "^5.0.6",
		"@capacitor/ios": "^5.2.2",
		"@capacitor/status-bar": "^5.0.6",
```

I am running version `^2.0.5` of this plugin. The CSS variables used to be set but, they don't seem to be working anymore. I am doing this in Vue. This is my test code:

```vue
<script setup lang="ts">
	import { ref, onMounted } from "vue";

	const props = defineProps<{ title: string }>();

	const val = ref("");

	onMounted(() => {
		val.value = getComputedStyle(document.documentElement)
			.getPropertyValue("--safe-area-top")
			.trim() || "Not set";
	});
</script>

<template>
	<div class="pt-safe flex bg-fg-primary self-stretch">
		<div class="flex w-full flex-row justify-between p-4 align-middle">
			<div class="pl-4 text-2xl text-text-secondary">
				{{ val }}
			</div>
			<div class="h-full">
				<i-mdi-close-circle
					class="h-8 w-8 text-bg-secondary active:text-bg-secondary-dark"
					@click="$router.back()"
				/>
			</div>
		</div>
	</div>
</template>
```

I'm not sure why it would work before but, not anymore after 1 month. Thoughts?

**Comment by AlwaysLoveme** [comment]
> I'm running Capacitor with the following versions:
> 
> ```
> 		"@capacitor/android": "^5.2.2",
> 		"@capacitor/core": "^5.2.2",
> 		"@capacitor/device": "^5.0.6",
> 		"@capacitor/ios": "^5.2.2",
> 		"@capacitor/status-bar": "^5.0.6",
> ```
> 
> I am running version `^2.0.5` of this plugin. The CSS variables used to be set but, they don't seem to be working anymore. I am doing this in Vue. This is my test code:
> 
> ```
> <script setup lang="ts">
> 	import { ref, onMounted } from "vue";
> 
> 	const props = defineProps<{ title: string }>();
> 
> 	const val = ref("");
> 
> 	onMounted(() => {
> 		val.value = getComputedStyle(document.documentElement)
> 			.getPropertyValue("--safe-area-top")
> 			.trim() || "Not set";
> 	});
> </script>
> 
> <template>
> 	<div class="pt-safe flex bg-fg-primary self-stretch">
> 		<div class="flex w-full flex-row justify-between p-4 align-middle">
> 			<div class="pl-4 text-2xl text-text-secondary">
> 				{{ val }}
> 			</div>
> 			<div class="h-full">
> 				<i-mdi-close-circle
> 					class="h-8 w-8 text-bg-secondary active:text-bg-secondary-dark"
> 					@click="$router.back()"
> 				/>
> 			</div>
> 		</div>
> 	</div>
> </template>
> ```
> 
> I'm not sure why it would work before but, not anymore after 1 month. Thoughts?

The plugin does not automatically set the value of --safe-area-top，it only provides information about SafeArea
