### ISSUE TITLE
[bug]: Incorrect Safe Areas on Pixel Phones

### ISSUE THREAD

**Issue by mahyarmirrashed** [AlwaysLoveme/capacitor-plugin-safe-area#21]
I'm using the Pixel phone emulations using the Android Device Manager. I find that the safe areas are inconsistent with what I would expect.

I am using a combination of the safe area and a padding of 16 pixels. So basically, I adjust the container of the top controls down with `absolute` and add `top: var(--safe-area-inset-top)`. The variable is set with `insets.top` from this plugin.

Here are the results on different devices:

Pixel 6a: 
![image-1](https://github.com/AlwaysLoveme/capacitor-plugin-safe-area/assets/59240843/670cdec7-1b83-456e-a0fe-ba0694e47931)

Pixel 6 Pro:
![image-1](https://github.com/AlwaysLoveme/capacitor-plugin-safe-area/assets/59240843/7473a19b-e0b9-40ab-b0b9-f63f0f6b94ee)

Pixel 7 Pro:
![image](https://github.com/AlwaysLoveme/capacitor-plugin-safe-area/assets/59240843/71d9d17f-1c03-4d52-83aa-94af4ed12a55)

The most correct one is the 6 Pro. The rest definitely have incorrect calculations for the top padding. Is there any way that we can fix this?

**Comment by AlwaysLoveme** [comment]
> I'm using the Pixel phone emulations using the Android Device Manager. I find that the safe areas are inconsistent with what I would expect.
> 
> I am using a combination of the safe area and a padding of 16 pixels. So basically, I adjust the container of the top controls down with `absolute` and add `top: var(--safe-area-inset-top)`. The variable is set with `insets.top` from this plugin.
> 
> Here are the results on different devices:
> 
> Pixel 6a: ![image-1](https://user-images.githubusercontent.com/59240843/266416027-670cdec7-1b83-456e-a0fe-ba0694e47931.png)
> 
> Pixel 6 Pro: ![image-1](https://user-images.githubusercontent.com/59240843/266416091-7473a19b-e0b9-40ab-b0b9-f63f0f6b94ee.png)
> 
> Pixel 7 Pro: ![image](https://user-images.githubusercontent.com/59240843/266416135-71d9d17f-1c03-4d52-83aa-94af4ed12a55.png)
> 
> The most correct one is the 6 Pro. The rest definitely have incorrect calculations for the top padding. Is there any way that we can fix this?

The Density value of each Android device is not always the same. The obtained top value will eventually be divided by density to get the final pixel value.

**Comment by mahyarmirrashed** [comment]
@AlwaysLoveme Can you explain that once for me? I'm sorry, I didn't really understand it. Is the density a value that is provided and something that I should currently be doing _or_ is it something that you plan to add in the future?

**Comment by mahyarmirrashed** [comment]
Following up on my previous comment @AlwaysLoveme .

**Comment by AlwaysLoveme** [comment]
> --safe-area-inset-top



> Following up on my previous comment @AlwaysLoveme .


"--safe-area-inset-top" obtains the height of the status bar on Android phones, but the height of the status bar of each mobile phone is not always the same, so the values obtained between each mobile phone are also different. within reason
