### ISSUE TITLE
[docs]: Add reference to Complementary Plugin

### ISSUE THREAD

**Issue by mahyarmirrashed** [AlwaysLoveme/capacitor-plugin-safe-area#22]
I'm wondering if it would be possible to include a reference to my repository, https://github.com/mahyarmirrashed/tailwindcss-safe-area-capacitor. It would be helpful for other developers who are using TailwindCSS and your plugin to know about this complementary plugin too since it's not all that popular.

**Comment by MaxRev-Dev** [comment]
@mahyarmirrashed The original plugin has an MIT license included, but you changed the copyright. You are not the author of this plugin, so you are not permitted to do this. I guess, you didn't read the MIT description.

> A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.

**Comment by mahyarmirrashed** [comment]
I was not aware that was how the MIT license worked. My understanding was pretty much: "go at it".

To confirm this, I did a little search online and found this SO article: https://softwareengineering.stackexchange.com/questions/218331/what-are-the-requirements-for-attribution-in-the-mit-license

Let me know your thoughts. I think I am following the most upvoted answer.

**Comment by MaxRev-Dev** [comment]
@mahyarmirrashed, I'm only referring to the missing copyright of the original author. 
This would be the right answer, saying you can only **add** your copyright notice. https://opensource.stackexchange.com/questions/8853/can-i-change-the-copyright-holder-name-and-year-of-an-mit-license. Anyways, for all software you are modifying, you have to preserve the original author.

Regarding the attribution, I doubt the author of this repo will include it here. The precedence will be on the original plugin repo and not a fork, if he will.

**Comment by mahyarmirrashed** [comment]
> @mahyarmirrashed, I'm only referring to the missing copyright of the original author. This would be the right answer, saying you can only **add** your copyright notice. https://opensource.stackexchange.com/questions/8853/can-i-change-the-copyright-holder-name-and-year-of-an-mit-license. Anyways, for all software you are modifying, you have to preserve the original author.
> 
> Regarding the attribution, I doubt the author of this repo will include it here. The precedence will be on the original plugin repo and not a fork, if he will.

Done.

**Comment by AlwaysLoveme** [comment]
> I'm wondering if it would be possible to include a reference to my repository, https://github.com/mahyarmirrashed/tailwindcss-safe-area-capacitor. It would be helpful for other developers who are using TailwindCSS and your plugin to know about this complementary plugin too since it's not all that popular.

already add to README

**Comment by mahyarmirrashed** [comment]
Thanks 😄
