### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by fabio-colella-md** [AlwaysLoveme/capacitor-plugin-safe-area#23]
Hi and thank you for your great plugin! 😃 

I'd like to know under what license is this software. Is it FOSS (e.g. MIT, Apache)? 😊

**Comment by AlwaysLoveme** [comment]
> Hi and thank you for your great plugin! 😃
> 
> I'd like to know under what license is this software. Is it FOSS (e.g. MIT, Apache)? 😊

Already updated
