### ISSUE TITLE
Bug: Android 12 and bottom navigation bar

### ISSUE THREAD

**Issue by malua** [AlwaysLoveme/capacitor-plugin-safe-area#25]
Hey there,

thanks for the plugin!

I recently discovered an issue with Android 12 and bottom navigation bars. In this case the plugin returns e.g. 41 pixel for the bottom inset, although there is no real inset.

Is this something that can be fixed? Or can I detect the navigation bar somehow?

I am thankful for all inputs :)

![image](https://github.com/AlwaysLoveme/capacitor-plugin-safe-area/assets/7237428/940fa429-6cbb-4259-926f-d24b81bfdc38)

**Comment by drewjosh** [comment]
I have experience the same issue on Android 11 on a Nokia 8.1. There is a bottom inset, even though the app view stops before the safe area:

![Screenshot_20240109-110104](https://github.com/AlwaysLoveme/capacitor-plugin-safe-area/assets/32765631/778286b6-8479-4533-a427-a7264dcba35c)

**Comment by malua** [comment]
Try `await SafeArea.setImmersiveNavigationBar();`. That fixed the problem for us!

**Comment by drewjosh** [comment]
> Try `await SafeArea.setImmersiveNavigationBar();`. That fixed the problem for us!

Amazing, thanks a lot for your fast response! 🚀 That worked as well for me. Many thanks!

**Comment by hk-skit** [comment]
Looks like the immersive mode doesn't consider application going to background/foreground state. The immersive mode is reset when the app is goes to background. This might fix it: https://stackoverflow.com/a/25129542/2879146

**Comment by malua** [comment]
@hk-skit I cannot see any issues with background/foreground. Would it help to just call it again in the appStateChange Listener, like this:

```
 App.addListener('appStateChange', appState => {
      if (appState.isActive) {
         this.setImmersiveNavigationBarAndReadSafeAreas();
       }
    });

private async setImmersiveNavigationBarAndReadSafeAreas() {
    await SafeArea.setImmersiveNavigationBar();

    const data = await SafeArea.getSafeAreaInsets();
    this.setVariables(data);
  }

  private setVariables(data: SafeAreaInsets) {
    for (const [key, value] of Object.entries(data.insets)) {
      document.documentElement.style.setProperty(
        `--ion-safe-area-${key}`,
        `${value}px`
      );
    }
  }
```
