### ISSUE TITLE
SafeArea plugin not implemented on ios error with Capacitor 6

### ISSUE THREAD

**Issue by drewjosh** [AlwaysLoveme/capacitor-plugin-safe-area#30]
Hello there,

Just updated to capacitor 6 and the current plugin version 3.0.1. When building to my iOS device (17.4.1) I get the error : "SafeArea plugin not implemented on ios".

I checked the related capacitor [troubleshooting guide](https://capacitorjs.com/docs/ios/troubleshooting), but nothing helped.

Someone else having the same issue? 

For now I switched back to capacitor 5 and plugin version 2.0.6

**Comment by zaosoula** [comment]
I have the same problem

**Comment by AlwaysLoveme** [comment]
> Hello there,
> 
> Just updated to capacitor 6 and the current plugin version 3.0.1. When building to my iOS device (17.4.1) I get the error : "SafeArea plugin not implemented on ios".
> 
> I checked the related capacitor [troubleshooting guide](https://capacitorjs.com/docs/ios/troubleshooting), but nothing helped.
> 
> Someone else having the same issue?
> 
> For now I switched back to capacitor 5 and plugin version 2.0.6

version 3.0.2 is fixed

**Comment by AlwaysLoveme** [comment]
> 2.0.6



> Hello there,
> 
> Just updated to capacitor 6 and the current plugin version 3.0.1. When building to my iOS device (17.4.1) I get the error : "SafeArea plugin not implemented on ios".
> 
> I checked the related capacitor [troubleshooting guide](https://capacitorjs.com/docs/ios/troubleshooting), but nothing helped.
> 
> Someone else having the same issue?
> 
> For now I switched back to capacitor 5 and plugin version 2.0.6

thanks for using this plugin, you can follow the steps below：
1. update @capacitor/android、@capacitor/core、@capacitor/ios、@capacitor/cli to latest with version@6+
2. update plugin capacitor-plugin-safe-area to version 3.0.2
3. Re-add IOS platform and build ios

**Comment by drewjosh** [comment]
> > 2.0.6
> 
> > Hello there,
> > Just updated to capacitor 6 and the current plugin version 3.0.1. When building to my iOS device (17.4.1) I get the error : "SafeArea plugin not implemented on ios".
> > I checked the related capacitor [troubleshooting guide](https://capacitorjs.com/docs/ios/troubleshooting), but nothing helped.
> > Someone else having the same issue?
> > For now I switched back to capacitor 5 and plugin version 2.0.6
> 
> thanks for using this plugin, you can follow the steps below：
> 
> 1. update @capacitor/android、@capacitor/core、@capacitor/ios、@capacitor/cli to latest with version@6+
> 2. update plugin capacitor-plugin-safe-area to version latest
> 3. Re-add IOS platform and build ios

Thanks! I just realised I had already updated in beginning of July and it's working again. Thanks a lot for your help!
