### ISSUE TITLE
error no such file or directory capacitor-plugin-safe-area/ios with capacitor 6

### ISSUE THREAD

**Issue by powehuda** [AlwaysLoveme/capacitor-plugin-safe-area#31]
greeting
I tried using "capacitor-plugin-safe-area": ​​"^3.0.2". When I did npx cap sync an error appeared that the iOS folder was not found.
I have also tried to update and re-add ios. but the result is still the same.
then I tried checking the node_modules/capacitor-plugin-safe-area folder. The iOS folder doesn't exist

<img width="201" alt="image" src="https://github.com/user-attachments/assets/1b15b43e-e1d3-4c50-bf87-d7c16ebd8822">

**Comment by AlwaysLoveme** [comment]
> greeting I tried using "capacitor-plugin-safe-area": ​​"^3.0.2". When I did npx cap sync an error appeared that the iOS folder was not found. I have also tried to update and re-add ios. but the result is still the same. then I tried checking the node_modules/capacitor-plugin-safe-area folder. The iOS folder doesn't exist
> 
> <img alt="image" width="201" src="https://private-user-images.githubusercontent.com/5734783/348446558-1b15b43e-e1d3-4c50-bf87-d7c16ebd8822.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4ODA4NjksIm5iZiI6MTcyMDg4MDU2OSwicGF0aCI6Ii81NzM0NzgzLzM0ODQ0NjU1OC0xYjE1YjQzZS1lMWQzLTRjNTAtYmY4Ny1kN2MxNmViZDg4MjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTNUMTQyMjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Y2NDdlZjI3MTFkM2ViMzMyZjI4MWZmYmI0Y2RlNWM0YzI0MDMwMGI0ZjdkNDE4NGIzZDM4NjNmNjkzMjJlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.J_JZGDREon0k9SQoMR4ZBLhSkh5-sc4kVYIl6rGqieY">


thanks for using this plugin，fixed in version 3.0.3
