### ISSUE TITLE
V 0.0.7 npm install issues

### ISSUE THREAD

**Issue by fabltd** [AlwaysLoveme/capacitor-plugin-safe-area#6]
When attepting to install the latest version the following error occours:

npm ERR! Found: @capacitor/core@4.1.0
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"^4.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^3.0.0" from capacitor-plugin-safe-area@0.0.7
npm ERR! node_modules/capacitor-plugin-safe-area
npm ERR!   capacitor-plugin-safe-area@"^0.0.7" from the root project

**Comment by AlwaysLoveme** [comment]
> When attepting to install the latest version the following error occours:
> 
> npm ERR! Found: @capacitor/core@4.1.0 npm ERR! node_modules/@capacitor/core npm ERR! @capacitor/core@"^4.1.0" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer @capacitor/core@"^3.0.0" from capacitor-plugin-safe-area@0.0.7 npm ERR! node_modules/capacitor-plugin-safe-area npm ERR! capacitor-plugin-safe-area@"^0.0.7" from the root project

HI , fixed in version 0.0.8

**Comment by Vshow101** [comment]
It is recommended to use the new version of [create-capacitor-plugin](https://github.com/ionic-team/create-capacitor-plugin) to create plugin that only support Capacitor 4.x, and release version 1.0 to avoid additional download of Capacitor 3.x-related dependencies in projects using Capacitor 4.x.

**Comment by AlwaysLoveme** [comment]
> It is recommended to use the new version of [create-capacitor-plugin](https://github.com/ionic-team/create-capacitor-plugin) to create plugin that only support Capacitor 4.x, and release version 1.0 to avoid additional download of Capacitor 3.x-related dependencies in projects using Capacitor 4.x.

Yeah，it is update to Capacitor4.x in the latest version
