### ISSUE TITLE
Add event listener because some devices can change the safe area

### ISSUE THREAD

**Issue by digaus** [AlwaysLoveme/capacitor-plugin-safe-area#8]
We could implement a layout listener like Keyboard Plugin does: 

https://github.com/ionic-team/capacitor-plugins/blob/main/keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/Keyboard.java#L61

With this we could emit an event so the safe areas can get updated

**Comment by AlwaysLoveme** [comment]
> We could implement a layout listener like Keyboard Plugin does: 
> 
> 
> 
> https://github.com/ionic-team/capacitor-plugins/blob/main/keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/Keyboard.java#L61
> 
> 
> 
> With this we could emit an event so the safe areas can get updated

this feature already in the latest version
